# Generated by Django 3.0.4 on 2020-07-01 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('licenses', '0003_auto_20200502_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stripe_customer',
            fields=[
                ('stripe_customer_id', models.TextField(editable=False, max_length=25)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_product_id', models.TextField(max_length=25)),
                ('stripe_subscription_id', models.TextField(max_length=25)),
                ('license', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='License', to='licenses.License')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Stripe_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
