# Generated by Django 3.0.4 on 2020-10-14 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stripe_customer',
            fields=[
                ('stripe_customer_id', models.CharField(editable=False, max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_product_id', models.CharField(max_length=50, null=True)),
                ('stripe_subscription_id', models.CharField(max_length=50, null=True)),
                ('stripe_default_card', models.CharField(max_length=50, null=True)),
                ('stripe_price_id', models.CharField(max_length=50, null=True)),
                ('license', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='License', to='licenses.License')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Stripe_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
