# Generated by Django 3.0.4 on 2020-07-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20200701_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripe_customer',
            name='stripe_default_card',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='stripe_customer',
            name='stripe_price_id',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='stripe_customer',
            name='stripe_product_id',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='stripe_customer',
            name='stripe_subscription_id',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
