# Generated by Django 3.0.4 on 2020-07-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20200709_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripe_customer',
            name='stripe_customer_id',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='stripe_customer',
            name='stripe_default_card',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stripe_customer',
            name='stripe_price_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stripe_customer',
            name='stripe_product_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stripe_customer',
            name='stripe_subscription_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
