# Generated by Django 3.0.4 on 2020-04-11 14:58

from django.db import migrations, models
import django_s3_storage.storage
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('max_file_size', models.IntegerField(default=100)),
                ('used_file_size', models.FloatField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('user_image', models.ImageField(null=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='filesec-userimage'), upload_to='')),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
