# Generated by Django 3.0.4 on 2020-05-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='max_file_size',
        ),
        migrations.RemoveField(
            model_name='user',
            name='used_file_size',
        ),
    ]
