# Generated by Django 3.0.4 on 2020-04-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200404_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='used_file_size',
            field=models.FloatField(default=0),
        ),
    ]
