# Generated by Django 3.0.4 on 2020-04-05 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_s3_storage.storage
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='filesec'), upload_to='')),
                ('name', models.TextField(default='noname')),
                ('private_key', models.TextField(default='nokey')),
                ('salt', models.BinaryField(default=b'\xc1\x10\xcd\x13\xc3\xf2\x8d=\xb9\xd7\x1e0$\x81\xdel', max_length=100)),
                ('format', models.TextField(default='noformat')),
                ('size', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
