# Generated by Django 3.0.4 on 2020-03-29 05:25

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20200328_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='encoding',
            field=models.TextField(default='noencoding'),
        ),
        migrations.AddField(
            model_name='files',
            name='format',
            field=models.TextField(default='noformat'),
        ),
        migrations.AddField(
            model_name='files',
            name='md5',
            field=models.TextField(default='nomd5'),
        ),
        migrations.AddField(
            model_name='files',
            name='name',
            field=models.TextField(default='noname'),
        ),
        migrations.AddField(
            model_name='files',
            name='private_key',
            field=models.TextField(default='nokey'),
        ),
        migrations.AddField(
            model_name='files',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='files',
            name='truncated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='filesec'), upload_to=''),
        ),
    ]
