# Generated by Django 3.0.4 on 2020-03-29 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20200329_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='encoding',
        ),
        migrations.RemoveField(
            model_name='files',
            name='md5',
        ),
        migrations.RemoveField(
            model_name='files',
            name='truncated',
        ),
    ]
