# Generated by Django 3.0.4 on 2020-09-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20200406_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
