# Generated by Django 3.0.4 on 2020-09-20 22:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_files_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='downloadHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('ip', models.TextField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloadHistory', to='files.Files')),
            ],
        ),
    ]
