# Generated by Django 3.0.4 on 2020-04-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20200329_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='salt',
            field=models.CharField(default=b'\x0eN\xe2\x8b\x91\x05]\xe8\xdc\xc0z\xa5\x93\xeb\xb5`', max_length=16),
        ),
    ]
