# Generated by Django 3.0.4 on 2020-09-20 22:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_downloadhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='downloadhistory',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
