# Generated by Django 3.0.4 on 2020-09-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20200920_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadhistory',
            name='download_success',
            field=models.BooleanField(default=False),
        ),
    ]
