# Generated by Django 3.0.4 on 2020-05-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_auto_20200502_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='totalSpace',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='license',
            name='usedSpace',
            field=models.FloatField(default=0),
        ),
    ]
