# Generated by Django 3.0.4 on 2020-07-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_auto_20200502_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='totalSpace',
            field=models.FloatField(default=50),
        ),
    ]
