# Generated by Django 3.0.4 on 2020-06-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userVerification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expiration_in_minutes',
            field=models.PositiveIntegerField(blank=True, default=10080, null=True),
        ),
    ]
