# Generated by Django 3.0.4 on 2020-06-11 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userVerification', '0003_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_token',
            new_name='token',
        ),
    ]
