# Generated by Django 3.0.4 on 2020-06-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userVerification', '0006_token_num_times_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token_type',
            field=models.CharField(choices=[('U_V', 'USER_VERIFICATION'), ('P_R', 'PASSWORD_RECOVERY')], max_length=10),
        ),
    ]
